language: php

sudo: false

env:
  global:
    secure: "DcTtBsjNY8p9hRjtIbTHc3r4ZU6ksqE3Nx7GE/ncIlrdoO0DTxxA/zkN6aizDpQiC6P7sz4FhhiK6ixJOLmnigNuij0v03bjhFApte36jT92iJgMKTGXIsH0Hj5XNlMBFpy0oAU8irhiPBK3lPoPJK+iadYdFA8yHdkEeYmsS/o="

php:
  - 5.5

cache:
  directories:
    - $HOME/.composer/cache

addons:
  code_climate:
    repo_token:
      secure: "jknkNfajYYpZfyUJuOlPS/3tXZeLrxcWFET1ZK+tc4UgfY69w4LSG9qrJnLfw0FdG32Rv9xlRkdaGCj7iBKl2p2pPnj0TfZ0a9PbQUA76g0+0ZFqwdYX8dmL1uPrdxp5P0n3Lakk10eJyjP9yX7E99OvSFt1ZCN4t4uIu/LIc0Q="

before_install:
  - composer self-update
  - composer validate
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - composer install --prefer-dist

script:
  - vendor/bin/php-cs-fixer fix --config-file=./.php_cs --dry-run --diff -v
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - 'curl --verbose -X POST -d @codeclimate.json -H "Content-Type: application/json" -H "User-Agent: Code Climate (PHP Test Reporter v0.1.2)"  https://codeclimate.com/test_reports'

notifications:
  email: false
