language: php

sudo: false

env:
  global:
    - secure: "OYEJGI9CVitqANQCCSxjxzpY0TBhpqJgySnRx4VQLJwpnOA0X3OOMLI6o09+OYet91CB/gJ7vdN/vWfFc09ev9M+OjVLNZ6DdQzr7Y7v/kt92vrUvKQW27G7z7mfsZZ9Je8eT3hHnbgFeWISj9CFfvaa6/7P4Wz1rPBO0/hNDXE="
    - secure: "vLO6MNtynfHTrTM76rq13lnwPqm8ULyTjFysYSCDIgUBidi4PMbmNjTf72LTrG9NboqWJNzItuiK5aQQCaJaDCr+603Getv2bKSpsPn1wnr51zYPGDsvKFL3e040JuDLs/4TslVtZbnsU9QxSwnixWEIOPF5ECBwMVk31+E+ak0="

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: WITH_CS=true
    - php: 7.0
    - php: 7.1
      env: WITH_COVERAGE=true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - if [[ "$WITH_COVERAGE" != "true" ]]; then phpenv config-rm xdebug.ini; fi
  - composer validate
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - composer install

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - mkdir -p build/logs

script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --configuration=phpunit.xml --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --configuration=phpunit.xml; fi
  - if [[ "$WITH_CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run; fi

after_success:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/test-reporter --coverage-report=build/logs/clover.xml; fi

notifications:
  email: false
