language: php

sudo: false

env:
  global:
    - secure: "QQEDmMEd9FctVNUHuuNnZaNPCQuQrVGF4hJbfBdkw2GhgqegIrTK47G0FaHl2y/lez82N3Jpuf/mpTO2jnw1aA+bIAJVo5NcY+0bTrm23SBS1lyyUs3TgTmkw6ByfLk3bmZ4TpRj8kAQdPK+aDWoK3Va0XdZt7swA39MugGYxvQ="

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

stages:
  - style
  - test

jobs:
  include:
    - stage: Style

      php: 7.0

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - composer validate
        - if [[ -n "$GITHUB_TOKEN" ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

      install:
        - composer install

      before_script:
        - mkdir -p $HOME/.php-cs-fixer

      script:
        - vendor/bin/php-cs-fixer fix --config=.php_cs --diff --dry-run --verbose

    - &TEST

      stage: Test

      php: 7.0

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - composer validate
        - if [[ -n "$GITHUB_TOKEN" ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

      install:
        - composer install

      script:
        - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi
        - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --configuration=test/Unit/phpunit.xml; fi
        - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-disable; fi

      after_success:
        - if [[ "$WITH_COVERAGE" == "true" ]]; then bash <(curl -s https://codecov.io/bash); fi

    - <<: *TEST

      php: 7.1

      env: WITH_COVERAGE=true

    - <<: *TEST

      php: 7.2

    - stage: Infection

      php: 7.1

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - composer validate
        - if [[ -n "$GITHUB_TOKEN" ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

      install:
        - composer install

      before_script:
        - xdebug-enable

      script:
        - vendor/bin/infection --min-covered-msi=80 --min-msi=80

notifications:
  email: false
