language: php

sudo: false

env:
  global:
    - secure: "DcTtBsjNY8p9hRjtIbTHc3r4ZU6ksqE3Nx7GE/ncIlrdoO0DTxxA/zkN6aizDpQiC6P7sz4FhhiK6ixJOLmnigNuij0v03bjhFApte36jT92iJgMKTGXIsH0Hj5XNlMBFpy0oAU8irhiPBK3lPoPJK+iadYdFA8yHdkEeYmsS/o="
    - secure: "vLO6MNtynfHTrTM76rq13lnwPqm8ULyTjFysYSCDIgUBidi4PMbmNjTf72LTrG9NboqWJNzItuiK5aQQCaJaDCr+603Getv2bKSpsPn1wnr51zYPGDsvKFL3e040JuDLs/4TslVtZbnsU9QxSwnixWEIOPF5ECBwMVk31+E+ak0="

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: WITH_CS=true
    - php: 7.0
    - php: 7.1
      env: WITH_COVERAGE=true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - if [[ "$WITH_COVERAGE" != "true" && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer validate
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - composer install --prefer-dist

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - mkdir -p build/logs

script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --configuration=phpunit.xml --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --configuration=phpunit.xml; fi
  - if [[ "$WITH_CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run; fi

after_success:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/test-reporter --coverage-report=build/logs/clover.xml; fi

notifications:
  email: false
